### PR TITLE
rats-tls: sgx rpm package info strip will cause to load sgx_stub_enclave.signed…

### PR DESCRIPTION
**Pull request by zhiminghufighting**
….so failed

Fixes: #1547
Signed-off-by: zhiminghufighting <zhiming.hu@intel.com>

### CODE REVIEW

**Comment by zhiminghufighting** [comment]
please see the validation log with screen:

**Comment by zhiminghufighting** [comment]
1643246866609_ECA8B7E9-B3B3-43fc-8A43-5217735254A0
1643246813354_735BA234-2EF8-4664-A657-B864B3FCE763
1643246712480_9EDA872E-6815-430c-ADF5-063F8E00B275
1643246703113_17767C47-1031-44f8-BB66-BDC919ADE0F8

**Comment by haosanzi** [comment]
Please test `la attestation` and `ecdsa_qve` verifier

**Comment by haosanzi** [comment]
Please change the commit header to `rats-tls: xxx`

**Comment by zhiminghufighting** [comment]
1643249824778_58CFF50B-2C01-411a-9192-C35DF395BE74
1643249844453_FC08E2E3-8071-4f77-9335-CC1B98AE44CA

**Pull request merged**
